from enum import Enum

class Permission(str, Enum):
    CREATE_USER = "CREATE_USER"
    UPDATE_USER = "UPDATE_USER"
    DELETE_USER = "DELETE_USER"
    VIEW_USER = "VIEW_USER"
    ASSIGN_ROLE = "ASSIGN_ROLE"
    APPROVE_TRANSACTION = "APPROVE_TRANSACTION"
    VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS"
    