"""Add user attributes

Revision ID: 916f93b326b0
Revises: 11daea44e738
Create Date: 2026-08-16 07:42:39.808498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '916f93b326b0'
down_revision = '11daea44e738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_attributes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('clearance_level', sa.Integer(), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_attributes_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_attributes_user_id'))

    op.drop_table('user_attributes')
    # ### end Alembic commands ###
