"""Add access resources

Revision ID: d27ec8fb43be
Revises: 916f93b326b0
Create Date: 2026-08-17 02:04:06.609994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27ec8fb43be'
down_revision = '916f93b326b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_resources',
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('required_clearance', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_resources_resource_type'), ['resource_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_resources_resource_type'))

    op.drop_table('access_resources')
    # ### end Alembic commands ###
